// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzprkibdeqoufoxqxatu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cHJraWJkZXFvdWZveHF4YXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTEzMDAsImV4cCI6MjA1ODMyNzMwMH0._eOdVTU26SFr5kPegl5HAeiuiprHKMRkqIbj7mM49UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);